config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :places, only: %i[index show] do
    resources :bookmarks, only: %i[create]
  end
  resources :bookmarks, except: %i[new create show] do
    resources :bookmark_tags, only: %i[create new]
  end

  resources :trips
  resources :bookmark_tags, only: %i[destroy]

  get 'profiles/definition', to: 'profiles#definition'
  post 'profiles/define', to: 'profiles#define'
  get 'profiles/results', to: 'profiles#results'
  # patch 'profiles/switch', to: 'profiles#switch'

  get 'user/dashboard', to: 'pages#dashboard'
  # get 'trips/search', to: "trips#search"
  # post 'trips', to: 'trips#research'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: "pages#home"
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :bookmarks
  has_many :places, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: { scope: :user_id }, presence: true

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
  end

  def show
    @trip = Trip.find(params[:id])

    # @active_bookmarks = @trip.bookmarks.select { |bmk| bmk.bookmarked? || bmk.reviewed? }
    # @trip_places = @active_bookmarks.map { |bmk| Place.find(bmk.place_id) }
    @trip_places = @trip.places

    @markers = @trip_places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude
      }
    end

  end

  def new
    @query = params[:query]
    @profile = current_user.profile_id
    @tags = Tag.all
  end

  def search
  end


  def research
    @tags = Tag.all
    @query = params[:query]
  end

  def create
    @place = Place.find(params[:place_id])
    @trip = Trip.new(name: trip_params, user_id: current_user.id)
    if @trip.save!
      @bookmark = Bookmark.new(place_id: @place.id, user_id: current_user.id, trip_id: @trip.id)
      @bookmark.save
      redirect_to place_path(@place)
    else
      render "places/#{@place.id}", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to user_dashboard_path
  end

  private

  def trip_params
    params.require(:name)
  end

end

app/views/trips/new.html.erb
<div class="container padding-bottom-wrapper" data-controller="research-form">
  <div class="form-container d-flex align-items-center vh-100">

    <div class="form-header">
      <div class="research-intro-container" data-research-form-target="intro">
        <h1 class="title-h1-form">Tell us more about <br>
        your trip to <span class= "text-yellow"> <%= @query.capitalize %></span></h1>
      </div>
    </div>

      <%# Comment faire pour que l'url reste le meme et n'affiche pas les paramètres de la recherche? %>
      <%= form_with(url: places_path, method: :get, data: {research_form_target: "body", research_form_question_index_value: 0 }, class: "d-none") do %>
        <%= hidden_field_tag :query, @query %>

        <div class="form-question m-10" data-research-form-target="question">
          <h3 class="title-h1-form">What's your<br><span class="text-yellow">mood</span> ?</h3>
          <div class="form-buttons">
            <% profile_names = ["Party Animal", "Bar Hopper", "Chill Seeker", "Gourmet Explorer"] %>
            <% profile_names.each do |name| %>
              <%= label_tag "profile_#{name}" do %>
                <%= radio_button_tag :profile, name, (current_user.profile.name == name ? true : false), data: { action: "click->research-form#next" }, class: "hidden-checkbox" %>
                <%= name %>
              <% end %>
            <% end %>
          </div>

          <div class="arrow-go align-right">
            <i class="fa-solid fa-chevron-right" data-action="click->research-form#next"></i>
          </div>
        </div>

        <div class="form-question m-10 d-none" data-research-form-target="question">
          <h3 class="title-h1-form">What do you want to<br><span class="text-yellow">discover</span> ?</h3>
          <p><em>You can select multiple places</em></p>
          <div class="form-buttons">
            <% Place.genres.keys.each do |key| %>
              <%= label_tag "genre_#{key}" do %>
                <%= check_box_tag "genre[]", key, false, { id: "genre_#{key}", class: "hidden-checkbox" } %>
                <%= key.capitalize %>
              <% end %>
            <% end %>
          </div>

          <div class="arrow-go align-right">
            <i class="fa-solid fa-chevron-right" data-action="click->research-form#next"></i>
          </div>
        </div>

        <div class="form-question d-none" data-research-form-target="question">

          <h3 class="title-h1-form">Fine tune your<br><span class= "text-purple">taste</span></h3>

          <p><em>You can select multiple tags</em></p>
          <div class="form-buttons">
            <% @tags.each do |tag| %>
              <%= label_tag "tag_#{tag.name}" do %>
                <%= check_box_tag "tags[]", tag.name, false, { id: "tag_#{tag.name}", class: "hidden-checkbox-tag tag-pill" } %>
                <i class="fa-solid fa-tag"></i>
                <%= tag.name %>
              <% end %>
            <% end %>
          </div>

          <div class="form-submit align-center m-2 ">
            <%= submit_tag "Get my recommandations", class: "button-main " %>
          </div>
        </div>


      <% end %>
  </div>
</div>

app/views/trips/show.html.erb
<div class="container padding-bottom-wrapper">
  <%= link_to user_dashboard_path, class: "link-secondary-perso" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>

  <%# IMAGE NE FONCTIONNE PAS - CF PRECEDENT CODE SI BESOIN %>
  <div class="place-show-image">
    <% if @trip_places.nil? %>
      <%= image_tag "https://media.istockphoto.com/id/1357365823/vector/default-image-icon-vector-missing-picture-page-for-website-design-or-mobile-app-no-photo.jpg?s=612x612&w=0&k=20&c=PM_optEhHBTZkuJQLlCjLz-v3zzxp-1mpNQZsdjrbns=" %>
    <% else %>
      <%= image_tag @trip_places.first.image %>
    <% end %>
  </div>
  <div class="place-show-details">
    <div class="place-show-top">
      <h1 style="margin: 16px 0px 0px">Your <%= @trip.name %></h1>
      <div class="address" style="margin-bottom: 16px">
          <p>Unique, as you</p>
      </div>
    </div>
  </div>
  <div class="mapbox-show-trip">
    <%= render "shared/geocoder", markers: @markers %>
  </div>
  <div style="margin-top: 24px">
  <h2>Mes lieux enregistrés</h2>
  </div>
      <% @trip_places.each do |place| %>
        <div class="place-cards">
          <% bookmark = Bookmark.where(trip_id: @trip.id, place_id: place.id).first %>
          <%= render "shared/trip_card", place: place, bookmark: bookmark%>
        </div>
      <% end %>
</div>