config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :places, only: %i[index show] do
    resources :bookmarks, only: %i[create]
  end
  resources :bookmarks, except: %i[new create show] do
    resources :bookmark_tags, only: %i[create new]
  end

  resources :trips
  resources :bookmark_tags, only: %i[destroy]

  get 'profiles/definition', to: 'profiles#definition'
  post 'profiles/define', to: 'profiles#define'
  get 'profiles/results', to: 'profiles#results'
  # patch 'profiles/switch', to: 'profiles#switch'

  get 'user/dashboard', to: 'pages#dashboard'
  # get 'trips/search', to: "trips#search"
  # post 'trips', to: 'trips#research'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: "pages#home"
end

app/views/shared/_big_place_card.html.erb
<%= link_to place_path(place) do %>
<div class="position-relative">
  <div class="place-big-card-image">
    <img src="<%= place.image? ? place.image : 'https://media.istockphoto.com/id/1357365823/vector/default-image-icon-vector-missing-picture-page-for-website-design-or-mobile-app-no-photo.jpg?s=612x612&w=0&k=20&c=PM_optEhHBTZkuJQLlCjLz-v3zzxp-1mpNQZsdjrbns=' %>" alt="<%= place.name %>" />
  </div>
    <% end %>
  <div class="big-card">
    <div class="bookmark <%= place.bookmarked?(current_user) ? 'bookmark--active' : '' %>">
      <i class="far fa-bookmark"></i>
    </div>
    <div class="big-card-details">
      <%= link_to place_path(place) do %>
      <h5 class="place-name"><%= place.name %></h5>
      <div class="address">
        <%= place.address %>
      </div>

      <div class="matching-score-big">
        <p><strong><span class="text-purple">Matching at <%= place.match(current_user) %> %</span></strong></p>
      </div>

      <div class="place-tag-list">
        <% place.tag_list(2).each do |tag| %>
          <div class="place-tag">
            <p><%= tag.first.downcase %></p>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  const bookmark = document.querySelector('.bookmark');
  const bookmarkIcon = document.querySelector('.fa-bookmark');

  bookmark.addEventListener('click', function() {
    bookmarkIcon.classList.toggle('far');
    bookmarkIcon.classList.toggle('fas');
  });
</script>
<% end %>

app/views/shared/_geocoder.html.erb
<div style="width: 100%; height: 100%; border-radius: 10px"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<%# PENSER A AJOUTER LA profile_picture via 'cl_image_tag current_user.profile_picture.attached? current_user.profile_picture.key : 'autre URL' ' %>
 <nav class="navbar_profile">
  <%= link_to root_path do %><i class="fa-solid fa-house" ></i><% end %>
  <%= link_to "#" do %><i class="fa-solid fa-map"></i><% end %>
  <%= link_to "#" do %><i class="fa-solid fa-plus" ></i><% end %>
  <%= link_to user_dashboard_path do %><i class="fa-solid fa-user" ></i><% end %>
  </nav>

app/views/shared/_place_card.html.erb
<%= link_to place_path(place) do %>
<div class="card">
  <div class="content-left">
  <%# end %>
    <!-- contenu de la partie gauche ici -->
    <div class="bookmark <%= place.bookmarked?(current_user) ? 'bookmark--active' : '' %>">
      <i class="far fa-bookmark"></i>
    </div>
    <div class="place-card-image" style="background-image: url('<% place.image? ? place.image : "../app/assets/images/no_image.jpg" %>')">
      <% if place.image? %>
        <%= image_tag place.image %>
      <% else %>
        <%= image_tag "https://media.istockphoto.com/id/1357365823/vector/default-image-icon-vector-missing-picture-page-for-website-design-or-mobile-app-no-photo.jpg?s=612x612&w=0&k=20&c=PM_optEhHBTZkuJQLlCjLz-v3zzxp-1mpNQZsdjrbns=" %>
      <% end %>
    </div>
  </div>
  <div class="content-right">
    <%#= link_to place_path(place) do %>
    <!-- contenu de la partie droite ici -->
    <h5 class="place-name"><%= place.name %></h5>
    <div class="address">
      <%= place.address %>
    </div>

    <div class="match-score-cards">
        <p><span class="text-purple"><strong>Matching at <%= place.match(current_user) %> %</span></strong></p>
    </div>

    <div class="place-tag-list">
      <% place.tag_list(2).each do |tag| %>
        <div class="place-tag">
          <p><%= tag.first.downcase %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>
 <% end %>

<script>
  const bookmark = document.querySelector('.bookmark');
  const bookmarkIcon = document.querySelector('.fa-bookmark');

  bookmark.addEventListener('click', function() {
    bookmarkIcon.classList.toggle('far');
    bookmarkIcon.classList.toggle('fas');
  });
</script>

app/views/shared/_register_form.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email,
                required: true,
                autofocus: true,
                placeholder: "youremail@gmail.com",
                input_html: { class: "formhome", autocomplete: "email" }%>
    <%= f.input :pseudo,
                required: true,
                autofocus: true,
                placeholder: "nickname",
                input_html: { class: "formhome", autocomplete: "pseudo" }%>
    <%= f.input :profile_picture, as: :file %>
    <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { class: "formhome", autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: true,
                input_html: { class: "formhome", autocomplete: "new-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "submit", class:'button-main w-100' %>
  </div>
<% end %>

<%#il manque la compilation de la class "formhome" da creare in CSS %>

app/views/shared/_sign_in_form.html.erb
<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
    <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password" } %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions submit-devise">
    <%= f.button :submit, "submit", class:'button-main w-100' %>
  </div>
<% end %>

app/views/shared/_trip_card.html.erb
<%= link_to place_path(place) do %>
  <div class="card">
    <div class="content-left">
      <!-- contenu de la partie gauche ici -->
      <div class="place-card-image">
        <% if place.image? %>
          <%= image_tag place.image %>
        <% else %>
          <%= image_tag 'https://media.istockphoto.com/id/1357365823/vector/default-image-icon-vector-missing-picture-page-for-website-design-or-mobile-app-no-photo.jpg?s=612x612&w=0&k=20&c=PM_optEhHBTZkuJQLlCjLz-v3zzxp-1mpNQZsdjrbns=' %>
        <% end %>
      <% end %>
      </div>
    </div>

    <%= link_to edit_bookmark_path(bookmark), data: {turbo: false}  do %>
    <div class="content-right">
      <!-- contenu de la partie droite ici -->
      <h5 class="place-name"><%= place.name %></h5>
      <div class="address">
        <%= place.address %>
      </div>
      <div class="visite button-main">
      <% if bookmark.reviewed? %>
        Reviewed
      <% else %>
        Leave a review
      <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_trip_card_index.html.erb
<%= link_to trip_path(my_trip) do %>
<div class="card">
  <div class="content-left">
    <!-- contenu de la partie gauche ici -->
    <div class="place-card-image">
      <% if my_trip.nil? %>
        <%= image_tag 'https://media.istockphoto.com/id/1357365823/vector/default-image-icon-vector-missing-picture-page-for-website-design-or-mobile-app-no-photo.jpg?s=612x612&w=0&k=20&c=PM_optEhHBTZkuJQLlCjLz-v3zzxp-1mpNQZsdjrbns=' %>
      <% else %>
        <%= image_tag my_trip.places.first.image %>
      <% end %>
    <% end %>
    </div>
  </div>
  <%= link_to trip_path(my_trip) do %>
  <div class="content-right">
    <!-- contenu de la partie droite ici -->
    <h5 class="place-name">
      <%= my_trip.name %>
    </h5>
    </div>
</div>
<% end %>