config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :places, only: %i[index show] do
    resources :bookmarks, only: %i[create]
  end
  resources :bookmarks, except: %i[new create show] do
    resources :bookmark_tags, only: %i[create new]
  end

  resources :trips
  resources :bookmark_tags, only: %i[destroy]

  get 'profiles/definition', to: 'profiles#definition'
  post 'profiles/define', to: 'profiles#define'
  get 'profiles/results', to: 'profiles#results'
  # patch 'profiles/switch', to: 'profiles#switch'

  get 'user/dashboard', to: 'pages#dashboard'
  # get 'trips/search', to: "trips#search"
  # post 'trips', to: 'trips#research'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: "pages#home"
end

app/views/pages/_info_window.html.erb
<%= link_to place_path(place) do %>
<h2><%= place.name %></h2>
<p><%= place.address %></p>
<% end %>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="top-actions d-flex justify-centent-end white">
    <%= link_to edit_user_registration_path, class: "edit-link" do %>
      <i class="fa-solid fa-gear"></i>
    <% end %>
    <%= link_to "Log out", destroy_user_session_path, class: "log-out-button", data: {turbo_method: :delete}%>
  </div>

  <div class="avatar_dashboard">
    <%= cl_image_tag current_user.profile_picture.attached? ? current_user.profile_picture.key : "vuwmei7psskhhh6vfua6" %>
  </div>
  <div class="user-pseudo">
    <h3><%= current_user.pseudo.capitalize %></h3>
  </div>
  <% if current_user.profile_id != nil %>
  <div class="profile-category">
    <%= link_to "#{current_user.profile.name}", profiles_definition_path %>
    <br>
  </div>
  <% end %>

  <div class="profile-boxes-trips">
    <div class="my-counts">
      <%= @my_trips.count %> <br>
      <% if @my_trips.count == 1 || @my_trips.count == 0 %>
        <p class="trips-string">Trip</p>
      <% else %>
        <p class="trips-string">Trips</p>
      <% end %>
    </div>

    <div class="my-counts">
      <%= @my_places.count %> <br>
      <% if @my_places.count == 1 || @my_places.count == 0 %>
        <p class="places-string">Place</p>
      <% else %>
        <p class="places-string">Places</p>
      <% end %>
    </div>

    <div class="my-counts">
      <%= @my_reviews %> <br>
      <% if @my_reviews == 1 || @my_reviews == 0 %>
        <p class="reviews-string">Review</p>
      <% else %>
        <p class="reviews-string">Reviews</p>
      <% end %>
    </div>
  </div>

  <div class="border-bottom-container">
    <p> </p>
  </div>


  <p class="your-best-places">Your <strong>best places</strong> in :</p>
  <% @my_trips.each do |trip| %>
        <%= render 'shared/trip_card_index', my_trip: trip %>
  <% end %>
    <%#= link_to "#{trip.name}", trip_path(trip.id), class: "btn btn-primary" %>
  <%#= link_to "Plan another trip", root_path, class: "button-main" %>
</div>

app/views/pages/home.html.erb
<%# PROPRE %>

<% if user_signed_in? == false || (user_signed_in? && current_user.profile == nil) %>

  <div data-controller='homepage'>
    <div class="container">
      <div class='page-is-changing'>
        <%= link_to '#bottom' do %>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>
    </div>

    <div class="registration-home-section div-with-bg" id='bottom'>
      <% if user_signed_in? %>
        <%= link_to profiles_definition_path, class:'w-100 text-center mb-5' do %>
          <button class="button-main" style='height:5vh'>Complete your profile</button>
        <% end %>
      <% else %>
        <!-- Aggiungere controller stimulus su tutta la pagina e dopo faccio set interval e poi la metodologia per fare scroller  -->
        <div class="container" data-controller='tabs'>
          <ul class="nav nav-justified mb-3" id="myTab">
            <button class="nav-link button-main" data-tabs-target='signInBtn' data-action='click->tabs#signIn'>Sign in</button>
            <button class="nav-link button-main" data-tabs-target='registerBtn' data-action='click->tabs#register'>Register</button>
          </ul>

          <div class="home-sign-in-form">
            <div class='d-none' data-tabs-target='signIn'>
              <%= render 'shared/sign_in_form' %>
            </div>

            <div class="d-none" data-tabs-target='register'>
              <%= render 'shared/register_form' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<% else %>

  <div class="home-top">
  <div class="position-relative">
    <div class="container-fluid position-absolute search-input">
      <% if params[:controller] == "pages" && params[:action] == "home" %>
        <div class="text">
          <h4>Going out like <br>
          a <strong>LOCAL</strong> in...</h4>
        </div>
        <%= form_with url: new_trip_path, method: :get, class: "d-flex me-2 " do %>
          <%= text_field_tag :query, params[:query], class: "search-navbar", placeholder: "Where will your new trip be?" %>
          <button class="btn btn-secondary ml-auto btn-search" type="submit">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="wrapper-index-map" style="height: 100vh;">
    <%= render "shared/geocoder", markers: @markers %>
  </div>

  <%= render "shared/navbar" %>
<% end %>