config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :places, only: %i[index show] do
    resources :bookmarks, only: %i[create]
  end
  resources :bookmarks, except: %i[new create show] do
    resources :bookmark_tags, only: %i[create new]
  end

  resources :trips
  resources :bookmark_tags, only: %i[destroy]

  get 'profiles/definition', to: 'profiles#definition'
  post 'profiles/define', to: 'profiles#define'
  get 'profiles/results', to: 'profiles#results'
  # patch 'profiles/switch', to: 'profiles#switch'

  get 'user/dashboard', to: 'pages#dashboard'
  # get 'trips/search', to: "trips#search"
  # post 'trips', to: 'trips#research'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: "pages#home"
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :bookmarks
  has_many :users, through: :bookmarks
  has_many :tags, through: :bookmarks
  has_many :bookmark_tags, through: :bookmarks

  validates :name, :address, presence: true

  enum genre: {
    restaurant: 0,
    bar: 1,
    club: 2
  }

  def match(current_user)
    actual_bookmarks = bookmarks.select { |bkm| bkm.rating != nil && bkm.user != current_user }

    total = actual_bookmarks.sum do |bookmark|

      if current_user.ponderation(bookmark.user).negative?
        case bookmark.rating
        when 5
          rating = 1
        when 4
          rating = 2
        when 1
          rating = 5
        when 2
          rating = 4
        when 3
          rating = 3 # A VOIR AVEC TIM CAR "LES 3 NE SONT PAS A PRENDRE EN COMPTE" :)
        end
        (rating * current_user.ponderation(bookmark.user)).abs
      else
        bookmark.rating * current_user.ponderation(bookmark.user)
      end

    end

    if total.zero?
      result = 50
    else
      result = ((total.to_f / actual_bookmarks.count )/ 5 * 100).to_i
      # result = 100 if result > 100
      result = (94..98).to_a.sample if result >= 100
    end

    return result

  end

  def bookmarked?(current_user)
    return self.users.any? { |user| user.id == current_user.id }
    # retravailler le test pour que ca ne sorte que les bookmarks "actifs" = pas ceux archivés
  end


  def set_ratings
    # Récupérer les bookmark_tags de chaque profil:

    # self.bookmark_tags.each do |bookark_tag|
    #   if bookark_tag.user.profile.party_animal?
    #     party_animal_bookmark_tags << bookark_tag
    #   elsif bookark_tags.user.profile.bar_hopper?
    #     bar_hopper_bookmark_tags << bookark_tag
    #   elsif bookark_tags.user.profile.chill_seeker?
    #     chill_seeker_bookmark_tags << bookark_tag
    #   else
    #     gourmet_explorer_bookmark_tags << bookark_tag
    #   end
    # end


    # pa_five = party_animal_bookmark_tags.count do |tag|
    #   tag.rating == 5
    # end



    # AVOIR UN HASH avec clé = la valeur du rating, valeur = le nombre de bookmark_tags avec de rating
  end

  def tag_list(number)
    tag_hash = {}
    self.tags.each do |tag|
      if tag_hash[tag.name].nil?
        tag_hash[tag.name] = 1
      else
        tag_hash[tag.name] += 1
      end
    end

    ordered_tags = tag_hash.to_a.sort_by! { |k, v| v }
    return ordered_tags.reverse.first(number)
  end



  # calculer la moyenne de chaque profil
  # définir la pondération de chaque profil


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index

    places = Place.all

    # ---- Afficher les résultats selon le lieu recherché ----
    @query = params[:query]
    if params[:query].present?
      sql_query = "address ILIKE :query"
      places = places.where(sql_query, query: "%#{params[:query]}%")
    end


    #  ---- Sélectionner les places selon le genre (resto, bar, club) recherché ----
    places = Place.where(genre: params[:genre])
    # ---- Je filtre par tags ----

    #  ---- J'ordonne par le ranking du matching ----
    sorted_places = places.sort_by do |place|
      place.match(current_user)
    end

    @search_places = sorted_places.reverse



    #  ---- variables pour la show ----
    @best_matches = @search_places.first(4)

    @reco_bars = @search_places.select(&:bar?)
    @reco_restaurants = @search_places.select(&:restaurant?)
    @reco_club = @search_places.select(&:club?)

    @trips = current_user.trips # Pour la modale d'ajout des bookmarks => avoir la liste des trips déjà créés de mon user
    @trip = Trip.new # Pour la modale d'ajout des bookmarks => créer une nouvelle instance de Trips

    # @markers = @places.geocoded.map do |place|
    #   {
      #     lat: place.latitude,
      #     lng: place.longitude
      #   }
    # end
  end

  def show
    @place = Place.find(params[:id])
    @recommendations = @place.bookmarks.select { |bmk| bmk.reviewed? }
    # @rating = (@recommendations.map { |reco| reco.rating }).sum / @recommendations.count
    @markers = [{
      lat: @place.latitude,
      lng: @place.longitude
      }]
    @bookmark = Bookmark.new
    @reco_places = Place.all.sample(3)
    @trips = current_user.trips.uniq
    @trip = Trip.new
    # @matching = @place.match(current_user)
    # A AJOUTER AVEC LES RECOS ASSOCIES = TAGS SIMILAIRES? OU MAJ DE PROFIL QUI LE PUSH => CHERCHER LES TAGS DU LIEU PARMI CES PROFILS?
  end


  private

  def place_params
    params.permit(:trip).require(:name, :address, :query)
  end

  def search_params
    params.require(:genre, :tags, :query)
  end

end

app/views/places/index.html.erb
<div class="container-places">
  <% if @query.present? && @search_places.empty? %>
    <h2><strong>No places in <%= @query.capitalize %></strong></h2>
    <% else %>
    <div class="text">
            <h4>Going out like <br>
            a LOCAL in <strong><%= @query.capitalize %></strong> :</h4>
            <% end %>
             </div>
  <button class="map-view" type="button">Map view</button>
  <h5 class="order">Order your matches :</h5>
  <div class="menu-container">
    <div class="menu">
      <select>
        <option value="">Relevance</option>
        <option value="1">Croissant</option>
        <option value="2">Décroissant</option>
      </select>
    </div>
    <div class="menu">
      <select>
        <option value="">Budget</option>
        <option value="1">Croissant</option>
        <option value="2">Décroissant</option>
      </select>
    </div>
    <div class="menu">
      <select>
        <option value="">Rating</option>
        <option value="1">Croissant</option>
        <option value="2">Décroissant</option>
      </select>
    </div>
  </div>
  <div class="bestmatches"><h3><strong>Best matches</strong> all categories</h3></div>

  <div class="cards-place-big">
    <% @best_matches.each do |match| %>
      <%= render "shared/big_place_card", place: match %>
    <% end %>
  </div>
</div>

<div class="container-reco">

  <% if @reco_club.count != 0 %>
    <div class="place-index-reco-top">
      <h3><strong>Best Club </strong>in <%= @query.capitalize %></h3>
      <div class="place-cards-scrollable">
        <% @reco_club.each do |place| %>
          <%= render "shared/place_card", place: place %>
        <% end %>
      </div>
    </div>
  <% end %>


  <% if @reco_bars.count != 0 %>
    <div class="place-index-reco-top">
      <h3><strong>Best Bar </strong>in <%= @query.capitalize %></h3>
      <div class="place-cards-scrollable">
        <% @reco_bars.each do |place| %>
          <%= render "shared/place_card", place: place %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @reco_restaurants.count != 0 %>
    <div class="place-index-reco-top">
      <h3><strong>Best Restaurant </strong>in <%= @query.capitalize %></h3>
      <div class="place-cards-scrollable">
        <% @reco_restaurants.each do |place| %>
          <%= render "shared/place_card", place: place %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/places/show.html.erb
  <%= link_to :back, class: "link-secondary-perso" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>

<div class="container padding-bottom-wrapper">

  <%# IMAGE NE FONCTIONNE PAS - CF PRECEDENT CODE SI BESOIN %>
  <div class="place-show-image">
    <% if @place.image? %>
      <%= image_tag @place.image %>
    <% else %>
      <%= image_tag "https://media.istockphoto.com/id/1357365823/vector/default-image-icon-vector-missing-picture-page-for-website-design-or-mobile-app-no-photo.jpg?s=612x612&w=0&k=20&c=PM_optEhHBTZkuJQLlCjLz-v3zzxp-1mpNQZsdjrbns=" %>
    <% end %>
  </div>

  <div class="place-show-details">
    <div class="place-show-top">
      <h1><%= @place.name %></h1>
      <div class="match-score-show">
        <p><span class="text-yellow"><strong>Matching at <%= @place.match(current_user) %> %</span></strong></p>
      </div>
      <div class="address">
        <i class="fa-solid fa-location-dot"></i>
        <%= @place.address %>
      </div>


      <div class="place-tag-list d-flex"> <%# REND UNIQUE CHAQUE TAG ET DONNE LE NB DE FOIS QU'IL A ETE ATTRIBUE: %>
        <% @place.tag_list(4).each do |tag| %>
          <div class="form-buttons-tag d-flex">
            <i class="fa-solid fa-tag d-flex"></i>
            <p><%= tag.first.downcase %></p>
          </div>
        <% end %>
      </div>

      <%#= LAISSER LE CHOIX DU TRIP AUQUEL INTEGRER LE BOOKMARK %>
      <% if @place.bookmarked?(current_user) %>
        <%#= link_to "Remove from my bookmarks", place_path(@place), data: {turbo_method: :destroy, turbo_confirm: "Are you sure?"} %>
        <button class="button-main">Added to your bookmarks</button>
      <% else %>
          <!-- Button trigger modal -->
          <button type="button" class="button-main" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Add to my bookmarks
          </button>
      <% end %>
    </div>


    <div class="border-bottom-container center">
      <p> </p>
    </div>


    <div class="place-show-descr">
      <h3>About</h3>
        <% if @place.description.nil? %>
          <p><em>No description yet</em></p>
        <% else %>
          <p><%= @place.description %></p>
        <% end %>

        <p><%#= @place.website %></p>
        <p><%= @place.phone_number %></p>

      <div class="place-show-map">
        <%= render "shared/geocoder", markers: @markers %>
      </div>
    </div>
  </div>

  <div class="border-bottom-container">
    <p> </p>
  </div>

  <div class="place-show-reco">
    <h3>Similar places you might like</h3>
      <% @reco_places.each do |place| %>
        <div class="place-cards">
          <%= render "shared/place_card", place: place %>
        </div>
      <% end %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <div class="modal-body align-self-center">
        <h4>Create a new trip:</h4>
          <div class="form-new-trip">
            <%= form_with model: @trip do %>
              <%= hidden_field_tag :place_id, @place.id %>
              <%= text_field_tag :name, params[:name], id: "trip_", placeholder: "New trip name" %>
              <%= submit_tag "Add", class: "button-form-popup"  %>
            <% end %>
          </div>
        <% if @trips.present? %>

          <div class="form-existing-trips">
            <h4>Or add to an existing one:</h4>
              <%= form_with url: place_bookmarks_path(@place), method: :post do |f| %>
                <div class="form-place d-flex">
                  <%= f.collection_select :trip_id, @trips, :id, :name, prompt: true %>
                  <%= f.submit "Add", class: "button-form-popup" %>
                </div>
              <% end %>
          </div>
        <% end %>
      </div>


    </div>
  </div>
</div>